### ISSUE TITLE
set ontime via msg.payload.ontime Error

### ISSUE THREAD

**Issue by marc-gist** [mrgadget/node-red-contrib-eztimer#41]
Latest is throwing the "Invalid object (msg.payload) input." error when sending in a `msg.payload.ontime` string formated as per docs.

`{"payload":{"ontime":"06:30:00"},"_msgid":"xxx"}`

**Comment by matt6575** [comment]
Same problem here. However things seems to function properly in spite of the error message.

**Comment by mrgadget** [comment]
Thanks guys, will get to it soon (likely this coming weekend) had a bunch of stuff on lately - sorry for delay.

**Comment by mrgadget** [comment]
Right.  Quick test leads me to assume that by latest you mean 1.2.4 (latest on npm).  1.2.5 (latest commit on here) doesn't exhibit the issue - I've just pushed another commit (12d5f0b) with some doco tweaks and a couple of code changes - if you guys could give it a go that'd be great - if you're not sure about dev builds, no probs, it should hopefully make it to npm in the next week.

**Comment by marc-gist** [comment]
Thanks, yes 1.2.4 on npm. once NR pickups the change I'll update and test.

**Comment by marc-gist** [comment]
node-red site still shows 1.2.4.
https://flows.nodered.org/node/node-red-contrib-eztimer

**Comment by mrgadget** [comment]
Ah yes it will. I'm not going to publish 1.2.5 to everyone until there's some more testing gone on. Will let you know when it's on npm.

**Comment by matt6575** [comment]
I can confirm this is fixed in 1.2.5

**Comment by mrgadget** [comment]
1.2.5 published to npm and pulled through to Node-RED packages.
